name: Docs

on:
  # always trigger
  push:
    paths:
      # Only run when rust or github files are changed
      - **/*.rs
      - .github/**
  pull_request:
    paths:
      # Only run when rust or github files are changed
      - **/*.rs
      - .github/**

jobs:

  # test doc links still work
  docs:
    name: Rustdocs are clean
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64 ]
        rust: [ nightly ]
    container:
      image: ${{ matrix.arch }}/rust
        RUSTDOCFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install python dev
        run: |
          apt update
          apt install -y libpython3.9-dev
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ matrix.rust }}
      - name: Run cargo doc
        run: |
          cargo doc --document-private-items --no-deps --workspace --all-features
